### ISSUE TITLE
error

### ISSUE THREAD

**Issue by djkloop** [HorlogeSkynet/archey4#38]
~/ archey 
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/archey", line 7, in <module>
    from archey.archey import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/archey/archey.py", line 519, in <module>
    '-o', 'comm', '--no-headers'], universal_newlines=True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ps', '-u501', '-o', 'comm', '--no-headers']' returned non-zero exit status 1.

**Comment by HorlogeSkynet** [comment]
Hi, could you fill the issue template please ?

**Comment by Phoenix1747** [comment]
**ErROr**

**Comment by HorlogeSkynet** [comment]
Archey currently does not support Mac / Windows platforms.
See this [Project](https://github.com/HorlogeSkynet/archey4/projects/3) for further information and future roadmap.
Although, any PR / discussion would be appreciated.

Cheers

**Comment by Si13n7** [comment]
**Additional info:**
_Archey4 supports Windows 10 indirectly through WSL._ 😉

**Comment by HorlogeSkynet** [comment]
Yeah thanks Roy, I meant "native Windows platforms" :wink: :ok_hand:

**Comment by HorlogeSkynet** [comment]
Darwin support has been released today as v4.11.0 release (cc @djkloop).
